/**
 * Copyright (C) 2014 - present by OpenGamma Inc. and the OpenGamma group of companies
 * <p>
 * Please see distribution for license.
 */
package com.opengamma.strata.finance.credit;

import com.opengamma.strata.collect.id.StandardId;
import com.opengamma.strata.finance.credit.fee.FeeLeg;
import com.opengamma.strata.finance.credit.general.GeneralTerms;
import com.opengamma.strata.finance.credit.protection.ProtectionTerms;
import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.io.Serializable;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

/**
 * A credit default swap.
 *
 * In a credit default swap one party (the protection seller) agrees to compensate another party
 * (the protection buyer) if a specified company or Sovereign (the reference entity)
 * experiences a credit event, indicating it is or may be unable to service its debts.
 * The protection seller is typically paid a fee and/or premium, expressed as an annualized
 * percent of the notional in basis points, regularly over the life of the transaction or
 * otherwise as agreed by the parties.
 * <p>
 */
@BeanDefinition
public final class CreditDefaultSwap
    implements CreditDefaultSwapProduct, ImmutableBean, Serializable {

  /**
   * security identifier
   */
  @PropertyDefinition(validate = "notNull")
  private final StandardId standardId;

  /**
   * This element contains all the data that appears in the section entitled "1. General Terms"
   * in the 2003 ISDA Credit Derivatives Confirmation
   */
  @PropertyDefinition(validate = "notNull")
  private final GeneralTerms generalTerms;

  /**
   * This element contains all the terms relevant to defining the fixed amounts/payments per
   * the applicable ISDA definitions.
   */
  @PropertyDefinition(validate = "notNull")
  private final FeeLeg feeLeg;

  /**
   * This element contains all the terms relevant to defining the applicable floating rate payer
   * calculation amount, credit events and associated conditions to settlement,
   * and reference obligations
   */
  @PropertyDefinition(validate = "notNull")
  private final ProtectionTerms protectionTerms;

  //-------------------------------------------------------------------------

  /**
   * Expands this credit default swap.
   * <p>
   * Expanding a credit default swap causes the dates to be adjusted according to the relevant
   * holiday calendar. Other one-off calculations may also be performed.
   *
   * @return the expended credit default swap
   * @throws RuntimeException if unable to expand due to an invalid schedule or definition
   */
  @Override
  public ExpandedCreditDefaultSwap expand() {
    return ExpandedCreditDefaultSwap.builder()
        .build();
  }

  public static CreditDefaultSwap of(
      StandardId standardId,
      GeneralTerms generalTerms,
      FeeLeg feeLeg,
      ProtectionTerms protectionTerms
  ) {
    return builder()
        .standardId(standardId)
        .generalTerms(generalTerms)
        .feeLeg(feeLeg)
        .protectionTerms(protectionTerms)
        .build();
  }


  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code CreditDefaultSwap}.
   * @return the meta-bean, not null
   */
  public static CreditDefaultSwap.Meta meta() {
    return CreditDefaultSwap.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(CreditDefaultSwap.Meta.INSTANCE);
  }

  /**
   * The serialization version id.
   */
  private static final long serialVersionUID = 1L;

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static CreditDefaultSwap.Builder builder() {
    return new CreditDefaultSwap.Builder();
  }

  private CreditDefaultSwap(
      StandardId standardId,
      GeneralTerms generalTerms,
      FeeLeg feeLeg,
      ProtectionTerms protectionTerms) {
    JodaBeanUtils.notNull(standardId, "standardId");
    JodaBeanUtils.notNull(generalTerms, "generalTerms");
    JodaBeanUtils.notNull(feeLeg, "feeLeg");
    JodaBeanUtils.notNull(protectionTerms, "protectionTerms");
    this.standardId = standardId;
    this.generalTerms = generalTerms;
    this.feeLeg = feeLeg;
    this.protectionTerms = protectionTerms;
  }

  @Override
  public CreditDefaultSwap.Meta metaBean() {
    return CreditDefaultSwap.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets security identifier
   * @return the value of the property, not null
   */
  public StandardId getStandardId() {
    return standardId;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets this element contains all the data that appears in the section entitled "1. General Terms"
   * in the 2003 ISDA Credit Derivatives Confirmation
   * @return the value of the property, not null
   */
  public GeneralTerms getGeneralTerms() {
    return generalTerms;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets this element contains all the terms relevant to defining the fixed amounts/payments per
   * the applicable ISDA definitions.
   * @return the value of the property, not null
   */
  public FeeLeg getFeeLeg() {
    return feeLeg;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets this element contains all the terms relevant to defining the applicable floating rate payer
   * calculation amount, credit events and associated conditions to settlement,
   * and reference obligations
   * @return the value of the property, not null
   */
  public ProtectionTerms getProtectionTerms() {
    return protectionTerms;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      CreditDefaultSwap other = (CreditDefaultSwap) obj;
      return JodaBeanUtils.equal(getStandardId(), other.getStandardId()) &&
          JodaBeanUtils.equal(getGeneralTerms(), other.getGeneralTerms()) &&
          JodaBeanUtils.equal(getFeeLeg(), other.getFeeLeg()) &&
          JodaBeanUtils.equal(getProtectionTerms(), other.getProtectionTerms());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash = hash * 31 + JodaBeanUtils.hashCode(getStandardId());
    hash = hash * 31 + JodaBeanUtils.hashCode(getGeneralTerms());
    hash = hash * 31 + JodaBeanUtils.hashCode(getFeeLeg());
    hash = hash * 31 + JodaBeanUtils.hashCode(getProtectionTerms());
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(160);
    buf.append("CreditDefaultSwap{");
    buf.append("standardId").append('=').append(getStandardId()).append(',').append(' ');
    buf.append("generalTerms").append('=').append(getGeneralTerms()).append(',').append(' ');
    buf.append("feeLeg").append('=').append(getFeeLeg()).append(',').append(' ');
    buf.append("protectionTerms").append('=').append(JodaBeanUtils.toString(getProtectionTerms()));
    buf.append('}');
    return buf.toString();
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code CreditDefaultSwap}.
   */
  public static final class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code standardId} property.
     */
    private final MetaProperty<StandardId> standardId = DirectMetaProperty.ofImmutable(
        this, "standardId", CreditDefaultSwap.class, StandardId.class);
    /**
     * The meta-property for the {@code generalTerms} property.
     */
    private final MetaProperty<GeneralTerms> generalTerms = DirectMetaProperty.ofImmutable(
        this, "generalTerms", CreditDefaultSwap.class, GeneralTerms.class);
    /**
     * The meta-property for the {@code feeLeg} property.
     */
    private final MetaProperty<FeeLeg> feeLeg = DirectMetaProperty.ofImmutable(
        this, "feeLeg", CreditDefaultSwap.class, FeeLeg.class);
    /**
     * The meta-property for the {@code protectionTerms} property.
     */
    private final MetaProperty<ProtectionTerms> protectionTerms = DirectMetaProperty.ofImmutable(
        this, "protectionTerms", CreditDefaultSwap.class, ProtectionTerms.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "standardId",
        "generalTerms",
        "feeLeg",
        "protectionTerms");

    /**
     * Restricted constructor.
     */
    private Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case -1284477768:  // standardId
          return standardId;
        case 1474273663:  // generalTerms
          return generalTerms;
        case -1278433112:  // feeLeg
          return feeLeg;
        case 2103975470:  // protectionTerms
          return protectionTerms;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public CreditDefaultSwap.Builder builder() {
      return new CreditDefaultSwap.Builder();
    }

    @Override
    public Class<? extends CreditDefaultSwap> beanType() {
      return CreditDefaultSwap.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code standardId} property.
     * @return the meta-property, not null
     */
    public MetaProperty<StandardId> standardId() {
      return standardId;
    }

    /**
     * The meta-property for the {@code generalTerms} property.
     * @return the meta-property, not null
     */
    public MetaProperty<GeneralTerms> generalTerms() {
      return generalTerms;
    }

    /**
     * The meta-property for the {@code feeLeg} property.
     * @return the meta-property, not null
     */
    public MetaProperty<FeeLeg> feeLeg() {
      return feeLeg;
    }

    /**
     * The meta-property for the {@code protectionTerms} property.
     * @return the meta-property, not null
     */
    public MetaProperty<ProtectionTerms> protectionTerms() {
      return protectionTerms;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -1284477768:  // standardId
          return ((CreditDefaultSwap) bean).getStandardId();
        case 1474273663:  // generalTerms
          return ((CreditDefaultSwap) bean).getGeneralTerms();
        case -1278433112:  // feeLeg
          return ((CreditDefaultSwap) bean).getFeeLeg();
        case 2103975470:  // protectionTerms
          return ((CreditDefaultSwap) bean).getProtectionTerms();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code CreditDefaultSwap}.
   */
  public static final class Builder extends DirectFieldsBeanBuilder<CreditDefaultSwap> {

    private StandardId standardId;
    private GeneralTerms generalTerms;
    private FeeLeg feeLeg;
    private ProtectionTerms protectionTerms;

    /**
     * Restricted constructor.
     */
    private Builder() {
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    private Builder(CreditDefaultSwap beanToCopy) {
      this.standardId = beanToCopy.getStandardId();
      this.generalTerms = beanToCopy.getGeneralTerms();
      this.feeLeg = beanToCopy.getFeeLeg();
      this.protectionTerms = beanToCopy.getProtectionTerms();
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case -1284477768:  // standardId
          return standardId;
        case 1474273663:  // generalTerms
          return generalTerms;
        case -1278433112:  // feeLeg
          return feeLeg;
        case 2103975470:  // protectionTerms
          return protectionTerms;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case -1284477768:  // standardId
          this.standardId = (StandardId) newValue;
          break;
        case 1474273663:  // generalTerms
          this.generalTerms = (GeneralTerms) newValue;
          break;
        case -1278433112:  // feeLeg
          this.feeLeg = (FeeLeg) newValue;
          break;
        case 2103975470:  // protectionTerms
          this.protectionTerms = (ProtectionTerms) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public CreditDefaultSwap build() {
      return new CreditDefaultSwap(
          standardId,
          generalTerms,
          feeLeg,
          protectionTerms);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the {@code standardId} property in the builder.
     * @param standardId  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder standardId(StandardId standardId) {
      JodaBeanUtils.notNull(standardId, "standardId");
      this.standardId = standardId;
      return this;
    }

    /**
     * Sets the {@code generalTerms} property in the builder.
     * @param generalTerms  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder generalTerms(GeneralTerms generalTerms) {
      JodaBeanUtils.notNull(generalTerms, "generalTerms");
      this.generalTerms = generalTerms;
      return this;
    }

    /**
     * Sets the {@code feeLeg} property in the builder.
     * @param feeLeg  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder feeLeg(FeeLeg feeLeg) {
      JodaBeanUtils.notNull(feeLeg, "feeLeg");
      this.feeLeg = feeLeg;
      return this;
    }

    /**
     * Sets the {@code protectionTerms} property in the builder.
     * @param protectionTerms  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder protectionTerms(ProtectionTerms protectionTerms) {
      JodaBeanUtils.notNull(protectionTerms, "protectionTerms");
      this.protectionTerms = protectionTerms;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(160);
      buf.append("CreditDefaultSwap.Builder{");
      buf.append("standardId").append('=').append(JodaBeanUtils.toString(standardId)).append(',').append(' ');
      buf.append("generalTerms").append('=').append(JodaBeanUtils.toString(generalTerms)).append(',').append(' ');
      buf.append("feeLeg").append('=').append(JodaBeanUtils.toString(feeLeg)).append(',').append(' ');
      buf.append("protectionTerms").append('=').append(JodaBeanUtils.toString(protectionTerms));
      buf.append('}');
      return buf.toString();
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
