/**
 * Copyright (C) 2015 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.platform.finance;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Optional;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.google.common.collect.ImmutableMap;
import com.opengamma.collect.id.StandardId;

/**
 * Additional information about a trade.
 * <p>
 * This allows additional information about a trade to be associated.
 * It is kept in a separate object as the information is optional for pricing.
 */
@BeanDefinition
public final class TradeInfo
    implements ImmutableBean, Attributable, Serializable {

  /**
   * An empty instance of {@code TradeInfo}.
   */
  public static final TradeInfo EMPTY = TradeInfo.builder().build();

  /**
   * The set of additional trade attributes.
   * <p>
   * Most data in the trade is available as bean properties.
   * Attributes are typically used to tag the object with additional information.
   */
  @PropertyDefinition(validate = "notNull", overrideGet = true)
  private final ImmutableMap<String, String> attributes;
  /**
   * The counterparty identifier, optional.
   * <p>
   * An identifier used to specify the counterparty of the trade.
   */
  @PropertyDefinition(get = "optional")
  private final StandardId counterparty;
  /**
   * The trade date, optional.
   */
  @PropertyDefinition(get = "optional")
  private final LocalDate tradeDate;
  /**
   * The trade time, optional.
   */
  @PropertyDefinition(get = "optional")
  private final LocalTime tradeTime;
  /**
   * The trade time-zone, optional.
   */
  @PropertyDefinition(get = "optional")
  private final ZoneId zone;
  /**
   * The settlement date, optional.
   */
  @PropertyDefinition(get = "optional")
  private final LocalDate settlementDate;

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code TradeInfo}.
   * @return the meta-bean, not null
   */
  public static TradeInfo.Meta meta() {
    return TradeInfo.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(TradeInfo.Meta.INSTANCE);
  }

  /**
   * The serialization version id.
   */
  private static final long serialVersionUID = 1L;

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static TradeInfo.Builder builder() {
    return new TradeInfo.Builder();
  }

  private TradeInfo(
      Map<String, String> attributes,
      StandardId counterparty,
      LocalDate tradeDate,
      LocalTime tradeTime,
      ZoneId zone,
      LocalDate settlementDate) {
    JodaBeanUtils.notNull(attributes, "attributes");
    this.attributes = ImmutableMap.copyOf(attributes);
    this.counterparty = counterparty;
    this.tradeDate = tradeDate;
    this.tradeTime = tradeTime;
    this.zone = zone;
    this.settlementDate = settlementDate;
  }

  @Override
  public TradeInfo.Meta metaBean() {
    return TradeInfo.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the set of additional trade attributes.
   * <p>
   * Most data in the trade is available as bean properties.
   * Attributes are typically used to tag the object with additional information.
   * @return the value of the property, not null
   */
  @Override
  public ImmutableMap<String, String> getAttributes() {
    return attributes;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the counterparty identifier, optional.
   * <p>
   * An identifier used to specify the counterparty of the trade.
   * @return the optional value of the property, not null
   */
  public Optional<StandardId> getCounterparty() {
    return Optional.ofNullable(counterparty);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the trade date, optional.
   * @return the optional value of the property, not null
   */
  public Optional<LocalDate> getTradeDate() {
    return Optional.ofNullable(tradeDate);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the trade time, optional.
   * @return the optional value of the property, not null
   */
  public Optional<LocalTime> getTradeTime() {
    return Optional.ofNullable(tradeTime);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the trade time-zone, optional.
   * @return the optional value of the property, not null
   */
  public Optional<ZoneId> getZone() {
    return Optional.ofNullable(zone);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the settlement date, optional.
   * @return the optional value of the property, not null
   */
  public Optional<LocalDate> getSettlementDate() {
    return Optional.ofNullable(settlementDate);
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      TradeInfo other = (TradeInfo) obj;
      return JodaBeanUtils.equal(getAttributes(), other.getAttributes()) &&
          JodaBeanUtils.equal(counterparty, other.counterparty) &&
          JodaBeanUtils.equal(tradeDate, other.tradeDate) &&
          JodaBeanUtils.equal(tradeTime, other.tradeTime) &&
          JodaBeanUtils.equal(zone, other.zone) &&
          JodaBeanUtils.equal(settlementDate, other.settlementDate);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash = hash * 31 + JodaBeanUtils.hashCode(getAttributes());
    hash = hash * 31 + JodaBeanUtils.hashCode(counterparty);
    hash = hash * 31 + JodaBeanUtils.hashCode(tradeDate);
    hash = hash * 31 + JodaBeanUtils.hashCode(tradeTime);
    hash = hash * 31 + JodaBeanUtils.hashCode(zone);
    hash = hash * 31 + JodaBeanUtils.hashCode(settlementDate);
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(224);
    buf.append("TradeInfo{");
    buf.append("attributes").append('=').append(getAttributes()).append(',').append(' ');
    buf.append("counterparty").append('=').append(counterparty).append(',').append(' ');
    buf.append("tradeDate").append('=').append(tradeDate).append(',').append(' ');
    buf.append("tradeTime").append('=').append(tradeTime).append(',').append(' ');
    buf.append("zone").append('=').append(zone).append(',').append(' ');
    buf.append("settlementDate").append('=').append(JodaBeanUtils.toString(settlementDate));
    buf.append('}');
    return buf.toString();
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code TradeInfo}.
   */
  public static final class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code attributes} property.
     */
    @SuppressWarnings({"unchecked", "rawtypes" })
    private final MetaProperty<ImmutableMap<String, String>> attributes = DirectMetaProperty.ofImmutable(
        this, "attributes", TradeInfo.class, (Class) ImmutableMap.class);
    /**
     * The meta-property for the {@code counterparty} property.
     */
    private final MetaProperty<StandardId> counterparty = DirectMetaProperty.ofImmutable(
        this, "counterparty", TradeInfo.class, StandardId.class);
    /**
     * The meta-property for the {@code tradeDate} property.
     */
    private final MetaProperty<LocalDate> tradeDate = DirectMetaProperty.ofImmutable(
        this, "tradeDate", TradeInfo.class, LocalDate.class);
    /**
     * The meta-property for the {@code tradeTime} property.
     */
    private final MetaProperty<LocalTime> tradeTime = DirectMetaProperty.ofImmutable(
        this, "tradeTime", TradeInfo.class, LocalTime.class);
    /**
     * The meta-property for the {@code zone} property.
     */
    private final MetaProperty<ZoneId> zone = DirectMetaProperty.ofImmutable(
        this, "zone", TradeInfo.class, ZoneId.class);
    /**
     * The meta-property for the {@code settlementDate} property.
     */
    private final MetaProperty<LocalDate> settlementDate = DirectMetaProperty.ofImmutable(
        this, "settlementDate", TradeInfo.class, LocalDate.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "attributes",
        "counterparty",
        "tradeDate",
        "tradeTime",
        "zone",
        "settlementDate");

    /**
     * Restricted constructor.
     */
    private Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case 405645655:  // attributes
          return attributes;
        case -1651301782:  // counterparty
          return counterparty;
        case 752419634:  // tradeDate
          return tradeDate;
        case 752903761:  // tradeTime
          return tradeTime;
        case 3744684:  // zone
          return zone;
        case -295948169:  // settlementDate
          return settlementDate;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public TradeInfo.Builder builder() {
      return new TradeInfo.Builder();
    }

    @Override
    public Class<? extends TradeInfo> beanType() {
      return TradeInfo.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code attributes} property.
     * @return the meta-property, not null
     */
    public MetaProperty<ImmutableMap<String, String>> attributes() {
      return attributes;
    }

    /**
     * The meta-property for the {@code counterparty} property.
     * @return the meta-property, not null
     */
    public MetaProperty<StandardId> counterparty() {
      return counterparty;
    }

    /**
     * The meta-property for the {@code tradeDate} property.
     * @return the meta-property, not null
     */
    public MetaProperty<LocalDate> tradeDate() {
      return tradeDate;
    }

    /**
     * The meta-property for the {@code tradeTime} property.
     * @return the meta-property, not null
     */
    public MetaProperty<LocalTime> tradeTime() {
      return tradeTime;
    }

    /**
     * The meta-property for the {@code zone} property.
     * @return the meta-property, not null
     */
    public MetaProperty<ZoneId> zone() {
      return zone;
    }

    /**
     * The meta-property for the {@code settlementDate} property.
     * @return the meta-property, not null
     */
    public MetaProperty<LocalDate> settlementDate() {
      return settlementDate;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case 405645655:  // attributes
          return ((TradeInfo) bean).getAttributes();
        case -1651301782:  // counterparty
          return ((TradeInfo) bean).counterparty;
        case 752419634:  // tradeDate
          return ((TradeInfo) bean).tradeDate;
        case 752903761:  // tradeTime
          return ((TradeInfo) bean).tradeTime;
        case 3744684:  // zone
          return ((TradeInfo) bean).zone;
        case -295948169:  // settlementDate
          return ((TradeInfo) bean).settlementDate;
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code TradeInfo}.
   */
  public static final class Builder extends DirectFieldsBeanBuilder<TradeInfo> {

    private Map<String, String> attributes = ImmutableMap.of();
    private StandardId counterparty;
    private LocalDate tradeDate;
    private LocalTime tradeTime;
    private ZoneId zone;
    private LocalDate settlementDate;

    /**
     * Restricted constructor.
     */
    private Builder() {
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    private Builder(TradeInfo beanToCopy) {
      this.attributes = beanToCopy.getAttributes();
      this.counterparty = beanToCopy.counterparty;
      this.tradeDate = beanToCopy.tradeDate;
      this.tradeTime = beanToCopy.tradeTime;
      this.zone = beanToCopy.zone;
      this.settlementDate = beanToCopy.settlementDate;
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case 405645655:  // attributes
          return attributes;
        case -1651301782:  // counterparty
          return counterparty;
        case 752419634:  // tradeDate
          return tradeDate;
        case 752903761:  // tradeTime
          return tradeTime;
        case 3744684:  // zone
          return zone;
        case -295948169:  // settlementDate
          return settlementDate;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @SuppressWarnings("unchecked")
    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case 405645655:  // attributes
          this.attributes = (Map<String, String>) newValue;
          break;
        case -1651301782:  // counterparty
          this.counterparty = (StandardId) newValue;
          break;
        case 752419634:  // tradeDate
          this.tradeDate = (LocalDate) newValue;
          break;
        case 752903761:  // tradeTime
          this.tradeTime = (LocalTime) newValue;
          break;
        case 3744684:  // zone
          this.zone = (ZoneId) newValue;
          break;
        case -295948169:  // settlementDate
          this.settlementDate = (LocalDate) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public TradeInfo build() {
      return new TradeInfo(
          attributes,
          counterparty,
          tradeDate,
          tradeTime,
          zone,
          settlementDate);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the {@code attributes} property in the builder.
     * @param attributes  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder attributes(Map<String, String> attributes) {
      JodaBeanUtils.notNull(attributes, "attributes");
      this.attributes = attributes;
      return this;
    }

    /**
     * Sets the {@code counterparty} property in the builder.
     * @param counterparty  the new value
     * @return this, for chaining, not null
     */
    public Builder counterparty(StandardId counterparty) {
      this.counterparty = counterparty;
      return this;
    }

    /**
     * Sets the {@code tradeDate} property in the builder.
     * @param tradeDate  the new value
     * @return this, for chaining, not null
     */
    public Builder tradeDate(LocalDate tradeDate) {
      this.tradeDate = tradeDate;
      return this;
    }

    /**
     * Sets the {@code tradeTime} property in the builder.
     * @param tradeTime  the new value
     * @return this, for chaining, not null
     */
    public Builder tradeTime(LocalTime tradeTime) {
      this.tradeTime = tradeTime;
      return this;
    }

    /**
     * Sets the {@code zone} property in the builder.
     * @param zone  the new value
     * @return this, for chaining, not null
     */
    public Builder zone(ZoneId zone) {
      this.zone = zone;
      return this;
    }

    /**
     * Sets the {@code settlementDate} property in the builder.
     * @param settlementDate  the new value
     * @return this, for chaining, not null
     */
    public Builder settlementDate(LocalDate settlementDate) {
      this.settlementDate = settlementDate;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(224);
      buf.append("TradeInfo.Builder{");
      buf.append("attributes").append('=').append(JodaBeanUtils.toString(attributes)).append(',').append(' ');
      buf.append("counterparty").append('=').append(JodaBeanUtils.toString(counterparty)).append(',').append(' ');
      buf.append("tradeDate").append('=').append(JodaBeanUtils.toString(tradeDate)).append(',').append(' ');
      buf.append("tradeTime").append('=').append(JodaBeanUtils.toString(tradeTime)).append(',').append(' ');
      buf.append("zone").append('=').append(JodaBeanUtils.toString(zone)).append(',').append(' ');
      buf.append("settlementDate").append('=').append(JodaBeanUtils.toString(settlementDate));
      buf.append('}');
      return buf.toString();
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
