queue_rules:
  - name: default
    merge_conditions:
      - "label=auto-merge"
      - "check-success=build"
    merge_method: squash

pull_request_rules:
  - name: Auto-Merge
    description: Merge branch once conditions pass
    conditions:
      - "label=auto-merge"
      - "status-success=build"
      - "#approved-reviews-by>=1"
      - "-conflict"
      - "title~=^((?!(wip|WIP)).)*$"
    actions:
      queue:
        name: default

  - name: Delete-Branch
    description: Delete branch once PR merged
    conditions:
      - "merged"
    actions:
      delete_head_branch: {}
