/**
 * Copyright (C) 2013 - present by OpenGamma Inc. and the OpenGamma group of companies
 * 
 * Please see distribution for license.
 */
package com.opengamma.sesame.marketdata.spec;

import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.core.historicaltimeseries.HistoricalTimeSeriesResolver;

/**
 * 
 */
@BeanDefinition
public class HistoricalMarketDataSpecification implements ImmutableBean, MarketDataSpecification {

  private static final long serialVersionUID = 1L;

  /**
   * The timeseries resolver key, a null value means to use the system default (see {@link HistoricalTimeSeriesResolver#resolve}).
   */
  @PropertyDefinition
  private final String _timeSeriesResolverKey;

  /**
   * Constructor indicating that the system default resolver key should be used.
   */
  public HistoricalMarketDataSpecification() {
    this(builder());
  }

  /**
   * Creates an instance, specifying the resolver key to be used.
   * 
   * @param timeSeriesResolverKey the timeseries resolver key, may be null
   */
  public HistoricalMarketDataSpecification(String timeSeriesResolverKey) {
    this(builder().timeSeriesResolverKey(timeSeriesResolverKey));
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code HistoricalMarketDataSpecification}.
   * @return the meta-bean, not null
   */
  public static HistoricalMarketDataSpecification.Meta meta() {
    return HistoricalMarketDataSpecification.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(HistoricalMarketDataSpecification.Meta.INSTANCE);
  }

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static HistoricalMarketDataSpecification.Builder builder() {
    return new HistoricalMarketDataSpecification.Builder();
  }

  /**
   * Restricted constructor.
   * @param builder  the builder to copy from, not null
   */
  protected HistoricalMarketDataSpecification(HistoricalMarketDataSpecification.Builder builder) {
    this._timeSeriesResolverKey = builder._timeSeriesResolverKey;
  }

  @Override
  public HistoricalMarketDataSpecification.Meta metaBean() {
    return HistoricalMarketDataSpecification.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the timeseries resolver key, a null value means to use the system default (see {@link HistoricalTimeSeriesResolver#resolve}).
   * @return the value of the property
   */
  public String getTimeSeriesResolverKey() {
    return _timeSeriesResolverKey;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      HistoricalMarketDataSpecification other = (HistoricalMarketDataSpecification) obj;
      return JodaBeanUtils.equal(getTimeSeriesResolverKey(), other.getTimeSeriesResolverKey());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash += hash * 31 + JodaBeanUtils.hashCode(getTimeSeriesResolverKey());
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(64);
    buf.append("HistoricalMarketDataSpecification{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  protected void toString(StringBuilder buf) {
    buf.append("timeSeriesResolverKey").append('=').append(JodaBeanUtils.toString(getTimeSeriesResolverKey())).append(',').append(' ');
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code HistoricalMarketDataSpecification}.
   */
  public static class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code timeSeriesResolverKey} property.
     */
    private final MetaProperty<String> _timeSeriesResolverKey = DirectMetaProperty.ofImmutable(
        this, "timeSeriesResolverKey", HistoricalMarketDataSpecification.class, String.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "timeSeriesResolverKey");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case 158445109:  // timeSeriesResolverKey
          return _timeSeriesResolverKey;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public HistoricalMarketDataSpecification.Builder builder() {
      return new HistoricalMarketDataSpecification.Builder();
    }

    @Override
    public Class<? extends HistoricalMarketDataSpecification> beanType() {
      return HistoricalMarketDataSpecification.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code timeSeriesResolverKey} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<String> timeSeriesResolverKey() {
      return _timeSeriesResolverKey;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case 158445109:  // timeSeriesResolverKey
          return ((HistoricalMarketDataSpecification) bean).getTimeSeriesResolverKey();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code HistoricalMarketDataSpecification}.
   */
  public static class Builder extends DirectFieldsBeanBuilder<HistoricalMarketDataSpecification> {

    private String _timeSeriesResolverKey;

    /**
     * Restricted constructor.
     */
    protected Builder() {
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    protected Builder(HistoricalMarketDataSpecification beanToCopy) {
      this._timeSeriesResolverKey = beanToCopy.getTimeSeriesResolverKey();
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case 158445109:  // timeSeriesResolverKey
          return _timeSeriesResolverKey;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case 158445109:  // timeSeriesResolverKey
          this._timeSeriesResolverKey = (String) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public HistoricalMarketDataSpecification build() {
      return new HistoricalMarketDataSpecification(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the {@code timeSeriesResolverKey} property in the builder.
     * @param timeSeriesResolverKey  the new value
     * @return this, for chaining, not null
     */
    public Builder timeSeriesResolverKey(String timeSeriesResolverKey) {
      this._timeSeriesResolverKey = timeSeriesResolverKey;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(64);
      buf.append("HistoricalMarketDataSpecification.Builder{");
      int len = buf.length();
      toString(buf);
      if (buf.length() > len) {
        buf.setLength(buf.length() - 2);
      }
      buf.append('}');
      return buf.toString();
    }

    protected void toString(StringBuilder buf) {
      buf.append("timeSeriesResolverKey").append('=').append(JodaBeanUtils.toString(_timeSeriesResolverKey)).append(',').append(' ');
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
