/**
 * Copyright (C) 2015 - present by OpenGamma Inc. and the OpenGamma group of companies
 * <p>
 * Please see distribution for license.
 */
package com.opengamma.strata.engine.config;

import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.strata.basics.CalculationTarget;
import com.opengamma.strata.engine.marketdata.mapping.MarketDataMappings;

/**
 * Configuration of a task that calculates the value of a single measure for a target.
 * <p>
 * It contains the target, configuration for the function that performs the calculation, and
 * mappings that specify the market data that is used in the calculation.
 */
@BeanDefinition
public final class CalculationTaskConfig implements ImmutableBean {

  /** The target for which the value will be calculated. */
  @PropertyDefinition(validate = "notNull")
  private final CalculationTarget target;

  /** Configuration of the function that will calculate the value. */
  @PropertyDefinition(validate = "notNull")
  private final EngineFunctionConfig engineFunctionConfig;

  /** Mappings that specify the market data that should be used in the calculation. */
  @PropertyDefinition(validate = "notNull")
  private final MarketDataMappings marketDataMappings;

  /** The rules for reporting the calculated values. */
  @PropertyDefinition(validate = "notNull")
  private final ReportingRules reportingRules;

  /**
   * Returns configuration for a task that will calculate a value for a target.
   *
   * @param target  the target for which the value will be calculated
   * @param engineFunctionConfig  configuration of the function that will calculate the value
   * @param marketDataMappings  mappings that specify the market data that should be used in the calculation
   * @param reportingRules  the reporting rules to control the output
   * @return configuration for a task that will calculate the value of a measure for a target
   */
  public static CalculationTaskConfig of(
      CalculationTarget target,
      EngineFunctionConfig engineFunctionConfig,
      MarketDataMappings marketDataMappings,
      ReportingRules reportingRules) {

    return new CalculationTaskConfig(target, engineFunctionConfig, marketDataMappings, reportingRules);
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code CalculationTaskConfig}.
   * @return the meta-bean, not null
   */
  public static CalculationTaskConfig.Meta meta() {
    return CalculationTaskConfig.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(CalculationTaskConfig.Meta.INSTANCE);
  }

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static CalculationTaskConfig.Builder builder() {
    return new CalculationTaskConfig.Builder();
  }

  private CalculationTaskConfig(
      CalculationTarget target,
      EngineFunctionConfig engineFunctionConfig,
      MarketDataMappings marketDataMappings,
      ReportingRules reportingRules) {
    JodaBeanUtils.notNull(target, "target");
    JodaBeanUtils.notNull(engineFunctionConfig, "engineFunctionConfig");
    JodaBeanUtils.notNull(marketDataMappings, "marketDataMappings");
    JodaBeanUtils.notNull(reportingRules, "reportingRules");
    this.target = target;
    this.engineFunctionConfig = engineFunctionConfig;
    this.marketDataMappings = marketDataMappings;
    this.reportingRules = reportingRules;
  }

  @Override
  public CalculationTaskConfig.Meta metaBean() {
    return CalculationTaskConfig.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the target for which the value will be calculated.
   * @return the value of the property, not null
   */
  public CalculationTarget getTarget() {
    return target;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets configuration of the function that will calculate the value.
   * @return the value of the property, not null
   */
  public EngineFunctionConfig getEngineFunctionConfig() {
    return engineFunctionConfig;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets mappings that specify the market data that should be used in the calculation.
   * @return the value of the property, not null
   */
  public MarketDataMappings getMarketDataMappings() {
    return marketDataMappings;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the rules for reporting the calculated values.
   * @return the value of the property, not null
   */
  public ReportingRules getReportingRules() {
    return reportingRules;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      CalculationTaskConfig other = (CalculationTaskConfig) obj;
      return JodaBeanUtils.equal(getTarget(), other.getTarget()) &&
          JodaBeanUtils.equal(getEngineFunctionConfig(), other.getEngineFunctionConfig()) &&
          JodaBeanUtils.equal(getMarketDataMappings(), other.getMarketDataMappings()) &&
          JodaBeanUtils.equal(getReportingRules(), other.getReportingRules());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash = hash * 31 + JodaBeanUtils.hashCode(getTarget());
    hash = hash * 31 + JodaBeanUtils.hashCode(getEngineFunctionConfig());
    hash = hash * 31 + JodaBeanUtils.hashCode(getMarketDataMappings());
    hash = hash * 31 + JodaBeanUtils.hashCode(getReportingRules());
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(160);
    buf.append("CalculationTaskConfig{");
    buf.append("target").append('=').append(getTarget()).append(',').append(' ');
    buf.append("engineFunctionConfig").append('=').append(getEngineFunctionConfig()).append(',').append(' ');
    buf.append("marketDataMappings").append('=').append(getMarketDataMappings()).append(',').append(' ');
    buf.append("reportingRules").append('=').append(JodaBeanUtils.toString(getReportingRules()));
    buf.append('}');
    return buf.toString();
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code CalculationTaskConfig}.
   */
  public static final class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code target} property.
     */
    private final MetaProperty<CalculationTarget> target = DirectMetaProperty.ofImmutable(
        this, "target", CalculationTaskConfig.class, CalculationTarget.class);
    /**
     * The meta-property for the {@code engineFunctionConfig} property.
     */
    private final MetaProperty<EngineFunctionConfig> engineFunctionConfig = DirectMetaProperty.ofImmutable(
        this, "engineFunctionConfig", CalculationTaskConfig.class, EngineFunctionConfig.class);
    /**
     * The meta-property for the {@code marketDataMappings} property.
     */
    private final MetaProperty<MarketDataMappings> marketDataMappings = DirectMetaProperty.ofImmutable(
        this, "marketDataMappings", CalculationTaskConfig.class, MarketDataMappings.class);
    /**
     * The meta-property for the {@code reportingRules} property.
     */
    private final MetaProperty<ReportingRules> reportingRules = DirectMetaProperty.ofImmutable(
        this, "reportingRules", CalculationTaskConfig.class, ReportingRules.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "target",
        "engineFunctionConfig",
        "marketDataMappings",
        "reportingRules");

    /**
     * Restricted constructor.
     */
    private Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case -880905839:  // target
          return target;
        case -1249489892:  // engineFunctionConfig
          return engineFunctionConfig;
        case -662537845:  // marketDataMappings
          return marketDataMappings;
        case -1647034519:  // reportingRules
          return reportingRules;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public CalculationTaskConfig.Builder builder() {
      return new CalculationTaskConfig.Builder();
    }

    @Override
    public Class<? extends CalculationTaskConfig> beanType() {
      return CalculationTaskConfig.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code target} property.
     * @return the meta-property, not null
     */
    public MetaProperty<CalculationTarget> target() {
      return target;
    }

    /**
     * The meta-property for the {@code engineFunctionConfig} property.
     * @return the meta-property, not null
     */
    public MetaProperty<EngineFunctionConfig> engineFunctionConfig() {
      return engineFunctionConfig;
    }

    /**
     * The meta-property for the {@code marketDataMappings} property.
     * @return the meta-property, not null
     */
    public MetaProperty<MarketDataMappings> marketDataMappings() {
      return marketDataMappings;
    }

    /**
     * The meta-property for the {@code reportingRules} property.
     * @return the meta-property, not null
     */
    public MetaProperty<ReportingRules> reportingRules() {
      return reportingRules;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -880905839:  // target
          return ((CalculationTaskConfig) bean).getTarget();
        case -1249489892:  // engineFunctionConfig
          return ((CalculationTaskConfig) bean).getEngineFunctionConfig();
        case -662537845:  // marketDataMappings
          return ((CalculationTaskConfig) bean).getMarketDataMappings();
        case -1647034519:  // reportingRules
          return ((CalculationTaskConfig) bean).getReportingRules();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code CalculationTaskConfig}.
   */
  public static final class Builder extends DirectFieldsBeanBuilder<CalculationTaskConfig> {

    private CalculationTarget target;
    private EngineFunctionConfig engineFunctionConfig;
    private MarketDataMappings marketDataMappings;
    private ReportingRules reportingRules;

    /**
     * Restricted constructor.
     */
    private Builder() {
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    private Builder(CalculationTaskConfig beanToCopy) {
      this.target = beanToCopy.getTarget();
      this.engineFunctionConfig = beanToCopy.getEngineFunctionConfig();
      this.marketDataMappings = beanToCopy.getMarketDataMappings();
      this.reportingRules = beanToCopy.getReportingRules();
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case -880905839:  // target
          return target;
        case -1249489892:  // engineFunctionConfig
          return engineFunctionConfig;
        case -662537845:  // marketDataMappings
          return marketDataMappings;
        case -1647034519:  // reportingRules
          return reportingRules;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case -880905839:  // target
          this.target = (CalculationTarget) newValue;
          break;
        case -1249489892:  // engineFunctionConfig
          this.engineFunctionConfig = (EngineFunctionConfig) newValue;
          break;
        case -662537845:  // marketDataMappings
          this.marketDataMappings = (MarketDataMappings) newValue;
          break;
        case -1647034519:  // reportingRules
          this.reportingRules = (ReportingRules) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public CalculationTaskConfig build() {
      return new CalculationTaskConfig(
          target,
          engineFunctionConfig,
          marketDataMappings,
          reportingRules);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the {@code target} property in the builder.
     * @param target  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder target(CalculationTarget target) {
      JodaBeanUtils.notNull(target, "target");
      this.target = target;
      return this;
    }

    /**
     * Sets the {@code engineFunctionConfig} property in the builder.
     * @param engineFunctionConfig  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder engineFunctionConfig(EngineFunctionConfig engineFunctionConfig) {
      JodaBeanUtils.notNull(engineFunctionConfig, "engineFunctionConfig");
      this.engineFunctionConfig = engineFunctionConfig;
      return this;
    }

    /**
     * Sets the {@code marketDataMappings} property in the builder.
     * @param marketDataMappings  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder marketDataMappings(MarketDataMappings marketDataMappings) {
      JodaBeanUtils.notNull(marketDataMappings, "marketDataMappings");
      this.marketDataMappings = marketDataMappings;
      return this;
    }

    /**
     * Sets the {@code reportingRules} property in the builder.
     * @param reportingRules  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder reportingRules(ReportingRules reportingRules) {
      JodaBeanUtils.notNull(reportingRules, "reportingRules");
      this.reportingRules = reportingRules;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(160);
      buf.append("CalculationTaskConfig.Builder{");
      buf.append("target").append('=').append(JodaBeanUtils.toString(target)).append(',').append(' ');
      buf.append("engineFunctionConfig").append('=').append(JodaBeanUtils.toString(engineFunctionConfig)).append(',').append(' ');
      buf.append("marketDataMappings").append('=').append(JodaBeanUtils.toString(marketDataMappings)).append(',').append(' ');
      buf.append("reportingRules").append('=').append(JodaBeanUtils.toString(reportingRules));
      buf.append('}');
      return buf.toString();
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
