/**
 * Copyright (C) 2015 - present by OpenGamma Inc. and the OpenGamma group of companies
 * 
 * Please see distribution for license.
 */
package com.opengamma.strata.examples.marketdata.curve;

import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.strata.market.curve.CurveGroupName;
import com.opengamma.strata.market.curve.CurveName;

/**
 * Identifies an instance of a specific curve.
 */
@BeanDefinition(builderScope = "private")
public final class LoadedCurveKey implements ImmutableBean {

  /**
   * The curve group.
   */
  @PropertyDefinition(validate = "notNull")
  private final CurveGroupName curveGroup;
  /**
   * The curve name.
   */
  @PropertyDefinition(validate = "notNull")
  private final CurveName curveName;

  /**
   * Creates an instance from strings.
   * 
   * @param curveGroup  the curve group
   * @param curveName  the curve name
   * @return the curve key
   */
  public static LoadedCurveKey of(String curveGroup, String curveName) {
    return of(CurveGroupName.of(curveGroup), CurveName.of(curveName));
  }

  /**
   * Creates an instance from typed strings.
   * 
   * @param curveGroup  the curve group
   * @param curveName  the curve name
   * @return the curve key
   */
  public static LoadedCurveKey of(CurveGroupName curveGroup, CurveName curveName) {
    return new LoadedCurveKey(curveGroup, curveName);
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code LoadedCurveKey}.
   * @return the meta-bean, not null
   */
  public static LoadedCurveKey.Meta meta() {
    return LoadedCurveKey.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(LoadedCurveKey.Meta.INSTANCE);
  }

  private LoadedCurveKey(
      CurveGroupName curveGroup,
      CurveName curveName) {
    JodaBeanUtils.notNull(curveGroup, "curveGroup");
    JodaBeanUtils.notNull(curveName, "curveName");
    this.curveGroup = curveGroup;
    this.curveName = curveName;
  }

  @Override
  public LoadedCurveKey.Meta metaBean() {
    return LoadedCurveKey.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the curve group.
   * @return the value of the property, not null
   */
  public CurveGroupName getCurveGroup() {
    return curveGroup;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the curve name.
   * @return the value of the property, not null
   */
  public CurveName getCurveName() {
    return curveName;
  }

  //-----------------------------------------------------------------------
  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      LoadedCurveKey other = (LoadedCurveKey) obj;
      return JodaBeanUtils.equal(getCurveGroup(), other.getCurveGroup()) &&
          JodaBeanUtils.equal(getCurveName(), other.getCurveName());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash = hash * 31 + JodaBeanUtils.hashCode(getCurveGroup());
    hash = hash * 31 + JodaBeanUtils.hashCode(getCurveName());
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(96);
    buf.append("LoadedCurveKey{");
    buf.append("curveGroup").append('=').append(getCurveGroup()).append(',').append(' ');
    buf.append("curveName").append('=').append(JodaBeanUtils.toString(getCurveName()));
    buf.append('}');
    return buf.toString();
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code LoadedCurveKey}.
   */
  public static final class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code curveGroup} property.
     */
    private final MetaProperty<CurveGroupName> curveGroup = DirectMetaProperty.ofImmutable(
        this, "curveGroup", LoadedCurveKey.class, CurveGroupName.class);
    /**
     * The meta-property for the {@code curveName} property.
     */
    private final MetaProperty<CurveName> curveName = DirectMetaProperty.ofImmutable(
        this, "curveName", LoadedCurveKey.class, CurveName.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "curveGroup",
        "curveName");

    /**
     * Restricted constructor.
     */
    private Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case -1869987120:  // curveGroup
          return curveGroup;
        case 771153946:  // curveName
          return curveName;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public BeanBuilder<? extends LoadedCurveKey> builder() {
      return new LoadedCurveKey.Builder();
    }

    @Override
    public Class<? extends LoadedCurveKey> beanType() {
      return LoadedCurveKey.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code curveGroup} property.
     * @return the meta-property, not null
     */
    public MetaProperty<CurveGroupName> curveGroup() {
      return curveGroup;
    }

    /**
     * The meta-property for the {@code curveName} property.
     * @return the meta-property, not null
     */
    public MetaProperty<CurveName> curveName() {
      return curveName;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -1869987120:  // curveGroup
          return ((LoadedCurveKey) bean).getCurveGroup();
        case 771153946:  // curveName
          return ((LoadedCurveKey) bean).getCurveName();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code LoadedCurveKey}.
   */
  private static final class Builder extends DirectFieldsBeanBuilder<LoadedCurveKey> {

    private CurveGroupName curveGroup;
    private CurveName curveName;

    /**
     * Restricted constructor.
     */
    private Builder() {
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case -1869987120:  // curveGroup
          return curveGroup;
        case 771153946:  // curveName
          return curveName;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case -1869987120:  // curveGroup
          this.curveGroup = (CurveGroupName) newValue;
          break;
        case 771153946:  // curveName
          this.curveName = (CurveName) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public LoadedCurveKey build() {
      return new LoadedCurveKey(
          curveGroup,
          curveName);
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(96);
      buf.append("LoadedCurveKey.Builder{");
      buf.append("curveGroup").append('=').append(JodaBeanUtils.toString(curveGroup)).append(',').append(' ');
      buf.append("curveName").append('=').append(JodaBeanUtils.toString(curveName));
      buf.append('}');
      return buf.toString();
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
