/**
 * Copyright (C) 2014 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.platform.finance.trade.swap;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.google.common.collect.ImmutableList;

/**
 * An expanded swap leg consisting of payment periods and accrual periods.
 * <p>
 * This defines a single swap leg in the form of a list of payment periods.
 * Each payment period consists of one or more accrual periods.
 */
@BeanDefinition
public final class ExpandedSwapLeg
    implements SwapLeg, ImmutableBean, Serializable {

  /** Serialization version. */
  private static final long serialVersionUID = 1L;

  /**
   * The payment periods that combine to form the swap leg.
   * <p>
   * Each payment period may be treated independently.
   */
  @PropertyDefinition(validate = "notEmpty")
  private final ImmutableList<SwapPaymentPeriod> paymentPeriods;
  /**
   * The details of whether the notional amount is exchanged between the counterparties.
   */
  @PropertyDefinition(validate = "notNull")
  private final NotionalExchange notionalExchange;

  // TODO: fees

  //-------------------------------------------------------------------------
  /**
   * Converts this swap leg to the equivalent expanded swap leg.
   * 
   * @return this
   */
  @Override
  public ExpandedSwapLeg toExpanded() {
    return this;
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code ExpandedSwapLeg}.
   * @return the meta-bean, not null
   */
  public static ExpandedSwapLeg.Meta meta() {
    return ExpandedSwapLeg.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(ExpandedSwapLeg.Meta.INSTANCE);
  }

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static ExpandedSwapLeg.Builder builder() {
    return new ExpandedSwapLeg.Builder();
  }

  private ExpandedSwapLeg(
      List<SwapPaymentPeriod> paymentPeriods,
      NotionalExchange notionalExchange) {
    JodaBeanUtils.notEmpty(paymentPeriods, "paymentPeriods");
    JodaBeanUtils.notNull(notionalExchange, "notionalExchange");
    this.paymentPeriods = ImmutableList.copyOf(paymentPeriods);
    this.notionalExchange = notionalExchange;
  }

  @Override
  public ExpandedSwapLeg.Meta metaBean() {
    return ExpandedSwapLeg.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the payment periods that combine to form the swap leg.
   * <p>
   * Each payment period may be treated independently.
   * @return the value of the property, not empty
   */
  public ImmutableList<SwapPaymentPeriod> getPaymentPeriods() {
    return paymentPeriods;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the details of whether the notional amount is exchanged between the counterparties.
   * @return the value of the property, not null
   */
  public NotionalExchange getNotionalExchange() {
    return notionalExchange;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      ExpandedSwapLeg other = (ExpandedSwapLeg) obj;
      return JodaBeanUtils.equal(getPaymentPeriods(), other.getPaymentPeriods()) &&
          JodaBeanUtils.equal(getNotionalExchange(), other.getNotionalExchange());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash += hash * 31 + JodaBeanUtils.hashCode(getPaymentPeriods());
    hash += hash * 31 + JodaBeanUtils.hashCode(getNotionalExchange());
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(96);
    buf.append("ExpandedSwapLeg{");
    buf.append("paymentPeriods").append('=').append(getPaymentPeriods()).append(',').append(' ');
    buf.append("notionalExchange").append('=').append(JodaBeanUtils.toString(getNotionalExchange()));
    buf.append('}');
    return buf.toString();
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code ExpandedSwapLeg}.
   */
  public static final class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code paymentPeriods} property.
     */
    @SuppressWarnings({"unchecked", "rawtypes" })
    private final MetaProperty<ImmutableList<SwapPaymentPeriod>> paymentPeriods = DirectMetaProperty.ofImmutable(
        this, "paymentPeriods", ExpandedSwapLeg.class, (Class) ImmutableList.class);
    /**
     * The meta-property for the {@code notionalExchange} property.
     */
    private final MetaProperty<NotionalExchange> notionalExchange = DirectMetaProperty.ofImmutable(
        this, "notionalExchange", ExpandedSwapLeg.class, NotionalExchange.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "paymentPeriods",
        "notionalExchange");

    /**
     * Restricted constructor.
     */
    private Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case -1674414612:  // paymentPeriods
          return paymentPeriods;
        case -159410813:  // notionalExchange
          return notionalExchange;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public ExpandedSwapLeg.Builder builder() {
      return new ExpandedSwapLeg.Builder();
    }

    @Override
    public Class<? extends ExpandedSwapLeg> beanType() {
      return ExpandedSwapLeg.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code paymentPeriods} property.
     * @return the meta-property, not null
     */
    public MetaProperty<ImmutableList<SwapPaymentPeriod>> paymentPeriods() {
      return paymentPeriods;
    }

    /**
     * The meta-property for the {@code notionalExchange} property.
     * @return the meta-property, not null
     */
    public MetaProperty<NotionalExchange> notionalExchange() {
      return notionalExchange;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -1674414612:  // paymentPeriods
          return ((ExpandedSwapLeg) bean).getPaymentPeriods();
        case -159410813:  // notionalExchange
          return ((ExpandedSwapLeg) bean).getNotionalExchange();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code ExpandedSwapLeg}.
   */
  public static final class Builder extends DirectFieldsBeanBuilder<ExpandedSwapLeg> {

    private List<SwapPaymentPeriod> paymentPeriods = new ArrayList<SwapPaymentPeriod>();
    private NotionalExchange notionalExchange;

    /**
     * Restricted constructor.
     */
    private Builder() {
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    private Builder(ExpandedSwapLeg beanToCopy) {
      this.paymentPeriods = new ArrayList<SwapPaymentPeriod>(beanToCopy.getPaymentPeriods());
      this.notionalExchange = beanToCopy.getNotionalExchange();
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case -1674414612:  // paymentPeriods
          return paymentPeriods;
        case -159410813:  // notionalExchange
          return notionalExchange;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @SuppressWarnings("unchecked")
    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case -1674414612:  // paymentPeriods
          this.paymentPeriods = (List<SwapPaymentPeriod>) newValue;
          break;
        case -159410813:  // notionalExchange
          this.notionalExchange = (NotionalExchange) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public ExpandedSwapLeg build() {
      return new ExpandedSwapLeg(
          paymentPeriods,
          notionalExchange);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the {@code paymentPeriods} property in the builder.
     * @param paymentPeriods  the new value, not empty
     * @return this, for chaining, not null
     */
    public Builder paymentPeriods(List<SwapPaymentPeriod> paymentPeriods) {
      JodaBeanUtils.notEmpty(paymentPeriods, "paymentPeriods");
      this.paymentPeriods = paymentPeriods;
      return this;
    }

    /**
     * Sets the {@code notionalExchange} property in the builder.
     * @param notionalExchange  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder notionalExchange(NotionalExchange notionalExchange) {
      JodaBeanUtils.notNull(notionalExchange, "notionalExchange");
      this.notionalExchange = notionalExchange;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(96);
      buf.append("ExpandedSwapLeg.Builder{");
      buf.append("paymentPeriods").append('=').append(JodaBeanUtils.toString(paymentPeriods)).append(',').append(' ');
      buf.append("notionalExchange").append('=').append(JodaBeanUtils.toString(notionalExchange));
      buf.append('}');
      return buf.toString();
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
