/**
 * Copyright (C) 2015 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.strata.finance.fx;

import static com.opengamma.strata.collect.ArgChecker.inOrderOrEqual;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.ImmutableValidator;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.strata.basics.LongShort;
import com.opengamma.strata.basics.PutCall;

/**
 * A vanilla FX option.
 * <p>
 * An FX option is a financial instrument that provides an option based on the future value of
 * a foreign exchange. The option is European, exercised only on the exercise date.
 * <p>
 * If the option is a call, the option holder has the right to enter into the specified exchange.
 * If the option is a put, the option holder has the right to enter into the opposite of the specified exchange.
 * <p>
 * For example, a call on a 'EUR 1.00 / USD -1.41' exchange is the option to
 * perform a foreign exchange on the expiration date, where USD 1.41 is paid to receive EUR 1.00.
 * A put on the same exchange is the option to pay EUR 1.00 and receive USD 1.41.
 */
@BeanDefinition
public class FxVanillaOption
    implements FxVanillaOptionProduct, ImmutableBean, Serializable {

  /**
   * Whether the option is put or call.
   * <p>
   * A call gives the owner the right, but not obligation, to exercise the underlying foreign exchange.
   * A put gives a similar option to exercise the inverse of the underlying.
   */
  @PropertyDefinition
  private final PutCall putCall;
  /**
   * Whether the option is long or short.
   * <p>
   * Long indicates that the owner wants the option to be in the money at expiry.
   * Short indicates that the owner wants the option to be out of the money at expiry.
   */
  @PropertyDefinition
  private final LongShort longShort;
  /**
   * The expiration date of the option.  
   * <p>
   * The option is European, and can only be exercised on the expiration date. 
   */
  @PropertyDefinition(validate = "notNull")
  private final LocalDate expirationDate;
  /**
   * The expiration time of the option.  
   * <p>
   * The expiration time is related to the expiration date and time-zone.
   */
  @PropertyDefinition(validate = "notNull")
  private final LocalTime expirationTime;
  /**
   * The time-zone of the expiration time.  
   * <p>
   * The expiration time-zone is related to the expiration date and time.
   */
  @PropertyDefinition(validate = "notNull")
  private final ZoneId expirationZone;
  /**
   * The underlying foreign exchange.
   * <p>
   * At expiry, if the option is in the money, this foreign exchange will occur.
   * A call option permits the exchange as specified to occur.
   * A put option permits the inverse exchange to occur.
   */
  @PropertyDefinition(validate = "notNull")
  private final FxExchange underlying;

  //-------------------------------------------------------------------------
  @ImmutableValidator
  private void validate() {
    inOrderOrEqual(
        expirationDate, underlying.getBaseCurrencyPayment().getDate(),
        "expirationDate", "underlying.baseCurrencyPayment.date");
    inOrderOrEqual(
        expirationDate, underlying.getCounterCurrencyPayment().getDate(),
        "expirationDate", "underlying.counterCurrencyPayment.date");
  }

  //-------------------------------------------------------------------------
  /**
   * Gets the expiration date-time.
   * <p>
   * The option expires at this date and time.
   * <p>
   * The result is returned by combining the expiration date, time and time-zone.
   * 
   * @return the expiration date and time
   */
  public ZonedDateTime getExpirationDateTime() {
    return expirationDate.atTime(expirationTime).atZone(expirationZone);
  }

  //-------------------------------------------------------------------------
  /**
   * Expands this FX option, trivially returning {@code this}.
   * 
   * @return this
   */
  @Override
  public FxVanillaOption expand() {
    return this;
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code FxVanillaOption}.
   * @return the meta-bean, not null
   */
  public static FxVanillaOption.Meta meta() {
    return FxVanillaOption.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(FxVanillaOption.Meta.INSTANCE);
  }

  /**
   * The serialization version id.
   */
  private static final long serialVersionUID = 1L;

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static FxVanillaOption.Builder builder() {
    return new FxVanillaOption.Builder();
  }

  /**
   * Restricted constructor.
   * @param builder  the builder to copy from, not null
   */
  protected FxVanillaOption(FxVanillaOption.Builder builder) {
    JodaBeanUtils.notNull(builder.expirationDate, "expirationDate");
    JodaBeanUtils.notNull(builder.expirationTime, "expirationTime");
    JodaBeanUtils.notNull(builder.expirationZone, "expirationZone");
    JodaBeanUtils.notNull(builder.underlying, "underlying");
    this.putCall = builder.putCall;
    this.longShort = builder.longShort;
    this.expirationDate = builder.expirationDate;
    this.expirationTime = builder.expirationTime;
    this.expirationZone = builder.expirationZone;
    this.underlying = builder.underlying;
    validate();
  }

  @Override
  public FxVanillaOption.Meta metaBean() {
    return FxVanillaOption.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets whether the option is put or call.
   * <p>
   * A call gives the owner the right, but not obligation, to exercise the underlying foreign exchange.
   * A put gives a similar option to exercise the inverse of the underlying.
   * @return the value of the property
   */
  public PutCall getPutCall() {
    return putCall;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets whether the option is long or short.
   * <p>
   * Long indicates that the owner wants the option to be in the money at expiry.
   * Short indicates that the owner wants the option to be out of the money at expiry.
   * @return the value of the property
   */
  public LongShort getLongShort() {
    return longShort;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the expiration date of the option.
   * <p>
   * The option is European, and can only be exercised on the expiration date.
   * @return the value of the property, not null
   */
  public LocalDate getExpirationDate() {
    return expirationDate;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the expiration time of the option.
   * <p>
   * The expiration time is related to the expiration date and time-zone.
   * @return the value of the property, not null
   */
  public LocalTime getExpirationTime() {
    return expirationTime;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the time-zone of the expiration time.
   * <p>
   * The expiration time-zone is related to the expiration date and time.
   * @return the value of the property, not null
   */
  public ZoneId getExpirationZone() {
    return expirationZone;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the underlying foreign exchange.
   * <p>
   * At expiry, if the option is in the money, this foreign exchange will occur.
   * A call option permits the exchange as specified to occur.
   * A put option permits the inverse exchange to occur.
   * @return the value of the property, not null
   */
  public FxExchange getUnderlying() {
    return underlying;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      FxVanillaOption other = (FxVanillaOption) obj;
      return JodaBeanUtils.equal(getPutCall(), other.getPutCall()) &&
          JodaBeanUtils.equal(getLongShort(), other.getLongShort()) &&
          JodaBeanUtils.equal(getExpirationDate(), other.getExpirationDate()) &&
          JodaBeanUtils.equal(getExpirationTime(), other.getExpirationTime()) &&
          JodaBeanUtils.equal(getExpirationZone(), other.getExpirationZone()) &&
          JodaBeanUtils.equal(getUnderlying(), other.getUnderlying());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash = hash * 31 + JodaBeanUtils.hashCode(getPutCall());
    hash = hash * 31 + JodaBeanUtils.hashCode(getLongShort());
    hash = hash * 31 + JodaBeanUtils.hashCode(getExpirationDate());
    hash = hash * 31 + JodaBeanUtils.hashCode(getExpirationTime());
    hash = hash * 31 + JodaBeanUtils.hashCode(getExpirationZone());
    hash = hash * 31 + JodaBeanUtils.hashCode(getUnderlying());
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(224);
    buf.append("FxVanillaOption{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  protected void toString(StringBuilder buf) {
    buf.append("putCall").append('=').append(JodaBeanUtils.toString(getPutCall())).append(',').append(' ');
    buf.append("longShort").append('=').append(JodaBeanUtils.toString(getLongShort())).append(',').append(' ');
    buf.append("expirationDate").append('=').append(JodaBeanUtils.toString(getExpirationDate())).append(',').append(' ');
    buf.append("expirationTime").append('=').append(JodaBeanUtils.toString(getExpirationTime())).append(',').append(' ');
    buf.append("expirationZone").append('=').append(JodaBeanUtils.toString(getExpirationZone())).append(',').append(' ');
    buf.append("underlying").append('=').append(JodaBeanUtils.toString(getUnderlying())).append(',').append(' ');
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code FxVanillaOption}.
   */
  public static class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code putCall} property.
     */
    private final MetaProperty<PutCall> putCall = DirectMetaProperty.ofImmutable(
        this, "putCall", FxVanillaOption.class, PutCall.class);
    /**
     * The meta-property for the {@code longShort} property.
     */
    private final MetaProperty<LongShort> longShort = DirectMetaProperty.ofImmutable(
        this, "longShort", FxVanillaOption.class, LongShort.class);
    /**
     * The meta-property for the {@code expirationDate} property.
     */
    private final MetaProperty<LocalDate> expirationDate = DirectMetaProperty.ofImmutable(
        this, "expirationDate", FxVanillaOption.class, LocalDate.class);
    /**
     * The meta-property for the {@code expirationTime} property.
     */
    private final MetaProperty<LocalTime> expirationTime = DirectMetaProperty.ofImmutable(
        this, "expirationTime", FxVanillaOption.class, LocalTime.class);
    /**
     * The meta-property for the {@code expirationZone} property.
     */
    private final MetaProperty<ZoneId> expirationZone = DirectMetaProperty.ofImmutable(
        this, "expirationZone", FxVanillaOption.class, ZoneId.class);
    /**
     * The meta-property for the {@code underlying} property.
     */
    private final MetaProperty<FxExchange> underlying = DirectMetaProperty.ofImmutable(
        this, "underlying", FxVanillaOption.class, FxExchange.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "putCall",
        "longShort",
        "expirationDate",
        "expirationTime",
        "expirationZone",
        "underlying");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case -219971059:  // putCall
          return putCall;
        case 116685664:  // longShort
          return longShort;
        case -668811523:  // expirationDate
          return expirationDate;
        case -668327396:  // expirationTime
          return expirationTime;
        case -668142853:  // expirationZone
          return expirationZone;
        case -1770633379:  // underlying
          return underlying;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public FxVanillaOption.Builder builder() {
      return new FxVanillaOption.Builder();
    }

    @Override
    public Class<? extends FxVanillaOption> beanType() {
      return FxVanillaOption.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code putCall} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<PutCall> putCall() {
      return putCall;
    }

    /**
     * The meta-property for the {@code longShort} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<LongShort> longShort() {
      return longShort;
    }

    /**
     * The meta-property for the {@code expirationDate} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<LocalDate> expirationDate() {
      return expirationDate;
    }

    /**
     * The meta-property for the {@code expirationTime} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<LocalTime> expirationTime() {
      return expirationTime;
    }

    /**
     * The meta-property for the {@code expirationZone} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<ZoneId> expirationZone() {
      return expirationZone;
    }

    /**
     * The meta-property for the {@code underlying} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<FxExchange> underlying() {
      return underlying;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -219971059:  // putCall
          return ((FxVanillaOption) bean).getPutCall();
        case 116685664:  // longShort
          return ((FxVanillaOption) bean).getLongShort();
        case -668811523:  // expirationDate
          return ((FxVanillaOption) bean).getExpirationDate();
        case -668327396:  // expirationTime
          return ((FxVanillaOption) bean).getExpirationTime();
        case -668142853:  // expirationZone
          return ((FxVanillaOption) bean).getExpirationZone();
        case -1770633379:  // underlying
          return ((FxVanillaOption) bean).getUnderlying();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code FxVanillaOption}.
   */
  public static class Builder extends DirectFieldsBeanBuilder<FxVanillaOption> {

    private PutCall putCall;
    private LongShort longShort;
    private LocalDate expirationDate;
    private LocalTime expirationTime;
    private ZoneId expirationZone;
    private FxExchange underlying;

    /**
     * Restricted constructor.
     */
    protected Builder() {
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    protected Builder(FxVanillaOption beanToCopy) {
      this.putCall = beanToCopy.getPutCall();
      this.longShort = beanToCopy.getLongShort();
      this.expirationDate = beanToCopy.getExpirationDate();
      this.expirationTime = beanToCopy.getExpirationTime();
      this.expirationZone = beanToCopy.getExpirationZone();
      this.underlying = beanToCopy.getUnderlying();
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case -219971059:  // putCall
          return putCall;
        case 116685664:  // longShort
          return longShort;
        case -668811523:  // expirationDate
          return expirationDate;
        case -668327396:  // expirationTime
          return expirationTime;
        case -668142853:  // expirationZone
          return expirationZone;
        case -1770633379:  // underlying
          return underlying;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case -219971059:  // putCall
          this.putCall = (PutCall) newValue;
          break;
        case 116685664:  // longShort
          this.longShort = (LongShort) newValue;
          break;
        case -668811523:  // expirationDate
          this.expirationDate = (LocalDate) newValue;
          break;
        case -668327396:  // expirationTime
          this.expirationTime = (LocalTime) newValue;
          break;
        case -668142853:  // expirationZone
          this.expirationZone = (ZoneId) newValue;
          break;
        case -1770633379:  // underlying
          this.underlying = (FxExchange) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public FxVanillaOption build() {
      return new FxVanillaOption(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the {@code putCall} property in the builder.
     * @param putCall  the new value
     * @return this, for chaining, not null
     */
    public Builder putCall(PutCall putCall) {
      this.putCall = putCall;
      return this;
    }

    /**
     * Sets the {@code longShort} property in the builder.
     * @param longShort  the new value
     * @return this, for chaining, not null
     */
    public Builder longShort(LongShort longShort) {
      this.longShort = longShort;
      return this;
    }

    /**
     * Sets the {@code expirationDate} property in the builder.
     * @param expirationDate  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder expirationDate(LocalDate expirationDate) {
      JodaBeanUtils.notNull(expirationDate, "expirationDate");
      this.expirationDate = expirationDate;
      return this;
    }

    /**
     * Sets the {@code expirationTime} property in the builder.
     * @param expirationTime  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder expirationTime(LocalTime expirationTime) {
      JodaBeanUtils.notNull(expirationTime, "expirationTime");
      this.expirationTime = expirationTime;
      return this;
    }

    /**
     * Sets the {@code expirationZone} property in the builder.
     * @param expirationZone  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder expirationZone(ZoneId expirationZone) {
      JodaBeanUtils.notNull(expirationZone, "expirationZone");
      this.expirationZone = expirationZone;
      return this;
    }

    /**
     * Sets the {@code underlying} property in the builder.
     * @param underlying  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder underlying(FxExchange underlying) {
      JodaBeanUtils.notNull(underlying, "underlying");
      this.underlying = underlying;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(224);
      buf.append("FxVanillaOption.Builder{");
      int len = buf.length();
      toString(buf);
      if (buf.length() > len) {
        buf.setLength(buf.length() - 2);
      }
      buf.append('}');
      return buf.toString();
    }

    protected void toString(StringBuilder buf) {
      buf.append("putCall").append('=').append(JodaBeanUtils.toString(putCall)).append(',').append(' ');
      buf.append("longShort").append('=').append(JodaBeanUtils.toString(longShort)).append(',').append(' ');
      buf.append("expirationDate").append('=').append(JodaBeanUtils.toString(expirationDate)).append(',').append(' ');
      buf.append("expirationTime").append('=').append(JodaBeanUtils.toString(expirationTime)).append(',').append(' ');
      buf.append("expirationZone").append('=').append(JodaBeanUtils.toString(expirationZone)).append(',').append(' ');
      buf.append("underlying").append('=').append(JodaBeanUtils.toString(underlying)).append(',').append(' ');
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
