/**
 * Copyright (C) 2014 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.sesame.component;

import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;
import org.threeten.bp.Period;

import com.opengamma.util.ArgumentChecker;

/**
 * Temporary bean to represent a period in Joda bean so it can be deserialised.
 */
@BeanDefinition(builderScope = "private")
public class RetrievalPeriod implements ImmutableBean {

  /**
   * The retrieval period.
   */
  @PropertyDefinition(validate = "notNull")
  private final Period _retrievalPeriod;

  /**
   * Create an instance with the specified period.
   *
   * @param period the required retrieval period
   * @return a RetrievalPeriod
   */
  public static RetrievalPeriod of(Period period) {
    return new RetrievalPeriod(period);
  }

  private RetrievalPeriod(Period period) {
    _retrievalPeriod = ArgumentChecker.notNull(period, "period");
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code RetrievalPeriod}.
   * @return the meta-bean, not null
   */
  public static RetrievalPeriod.Meta meta() {
    return RetrievalPeriod.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(RetrievalPeriod.Meta.INSTANCE);
  }

  /**
   * Restricted constructor.
   * @param builder  the builder to copy from, not null
   */
  protected RetrievalPeriod(RetrievalPeriod.Builder builder) {
    JodaBeanUtils.notNull(builder._retrievalPeriod, "retrievalPeriod");
    this._retrievalPeriod = builder._retrievalPeriod;
  }

  @Override
  public RetrievalPeriod.Meta metaBean() {
    return RetrievalPeriod.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the retrieval period.
   * @return the value of the property, not null
   */
  public Period getRetrievalPeriod() {
    return _retrievalPeriod;
  }

  //-----------------------------------------------------------------------
  @Override
  public RetrievalPeriod clone() {
    return this;
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      RetrievalPeriod other = (RetrievalPeriod) obj;
      return JodaBeanUtils.equal(getRetrievalPeriod(), other.getRetrievalPeriod());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash += hash * 31 + JodaBeanUtils.hashCode(getRetrievalPeriod());
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(64);
    buf.append("RetrievalPeriod{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  protected void toString(StringBuilder buf) {
    buf.append("retrievalPeriod").append('=').append(JodaBeanUtils.toString(getRetrievalPeriod())).append(',').append(' ');
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code RetrievalPeriod}.
   */
  public static class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code retrievalPeriod} property.
     */
    private final MetaProperty<Period> _retrievalPeriod = DirectMetaProperty.ofImmutable(
        this, "retrievalPeriod", RetrievalPeriod.class, Period.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "retrievalPeriod");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case -1497501163:  // retrievalPeriod
          return _retrievalPeriod;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public RetrievalPeriod.Builder builder() {
      return new RetrievalPeriod.Builder();
    }

    @Override
    public Class<? extends RetrievalPeriod> beanType() {
      return RetrievalPeriod.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code retrievalPeriod} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Period> retrievalPeriod() {
      return _retrievalPeriod;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -1497501163:  // retrievalPeriod
          return ((RetrievalPeriod) bean).getRetrievalPeriod();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code RetrievalPeriod}.
   */
  private static class Builder extends DirectFieldsBeanBuilder<RetrievalPeriod> {

    private Period _retrievalPeriod;

    /**
     * Restricted constructor.
     */
    protected Builder() {
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case -1497501163:  // retrievalPeriod
          return _retrievalPeriod;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case -1497501163:  // retrievalPeriod
          this._retrievalPeriod = (Period) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public RetrievalPeriod build() {
      return new RetrievalPeriod(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(64);
      buf.append("RetrievalPeriod.Builder{");
      int len = buf.length();
      toString(buf);
      if (buf.length() > len) {
        buf.setLength(buf.length() - 2);
      }
      buf.append('}');
      return buf.toString();
    }

    protected void toString(StringBuilder buf) {
      buf.append("retrievalPeriod").append('=').append(JodaBeanUtils.toString(_retrievalPeriod)).append(',').append(' ');
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
