name: ogbot

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
    - uses: OpenGamma/OGBot@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
